- 🟥🪟 Hello @B2theNJ
- 🟧 Mii interested in ...
- 🟨 Pi currently learning ...
- 🟩🎈🎈🎈🎈 Wii looking to collaborate on ...
- 🟦 How to reach Mii ...
- 🟪⛳ Pronouns: #! ...
- ⚡🏌️‍♂️ Fun fact: eme ...

<!---
B2theNJ/B2theNJ is a ✨ special ✨ repository because its `README.md` (this file) appears on your GitHub profile.
You can click the Preview link to take a look at your changes.
--->
